name: "SourceGuard Code Analysis"
description: ""

inputs:
  SG_CLIENT_ID:
    description: ""
    required: true
  SG_SECRET_KEY:
    description: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Running SourceGuard code analysis
      run: |
        echo ${{ inputs.SG_CLIENT_ID }} >> $SG_CLIENT_ID
        echo ${{ inputs.SG_SECRET_KEY }} >> $SG_SECRET_KEY
        /sourceguard-cli --src ./
