name: SourceGuard Scan
on: [push, pull_request]
jobs:
  code-analysis:
    runs-on: ubuntu-latest
    container:
      image: sourceguard/sourceguard-cli
    env:
      SG_CLIENT_ID: ${{ secrets.SG_CLIENT_ID }}
      SG_SECRET_KEY: ${{ secrets.SG_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running SourceGuard code analysis
        run: /sourceguard-cli --src ./
